title: Hai Duong Nguyen
description: Data Analyst in Banking | Machine Learning | Time Series
theme: jekyll-theme-cayman

google_analytics: G-GZCJYZ4VZ5

# <!-- Google tag (gtag.js) -->
# <script async src="https://www.googletagmanager.com/gtag/js?id=G-GZCJYZ4VZ5"></script>
# <script>
#   window.dataLayer = window.dataLayer || [];
#   function gtag(){dataLayer.push(arguments);}
#   gtag('js', new Date());

#   gtag('config', 'G-GZCJYZ4VZ5');
# </script>